<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

        <title>My assignment 10</title>

        <link href="style.css" media="screen" rel="stylesheet" type="text/css" />

    </head>
    <body>

        <div class="header">

            <h1>Final Project</h1>
            <p>
            For my final project I designed an Automaton <br/>
             <br/>
              <br/>
            </p>
            <p>
            <img src="History.png" width=1000></a>
            </p>
            <p>
            <br/>
            <br/>

            </p>
            <p>
            <img src="giphy.gif" width=600></a>
            </p><br/>
            <br/>
            <p>

            <br/>
            INSPIRATION & GOAL
            <br/>
            I was inspired by a rustic example of an Automaton of a pig with wings. My goal is to adapt<br/>
            the same principles to create an Automaton featuring dragonfly wings that appear to flap by<br/>
            the turn of a crank.
            <br/>
            <br/>
        RESEARCH & SKETCHING A PLAN<br/>
            With no engineering in my background this required me to analyse the simple mechanics<br/>
            required to cause an upward/downward motion. I would also have to create housing for the mechanism,<br/>
            and the 'thing' to be moved. I worked out solutions by sketching, and looking up the mechanics of motion<br/>
            online.
            <br/><br/>
            <img src="7_how.JPG" width=600></a>
            </p>
            <br/><br/>
            <p>
            <img src="7_plan.JPG" width=600></a>
            </p>
            <p>
            MOTION <br/>
            • I first attempted to draw a mechanism that had 3 parts, a round "container" to hold the steel <br/>
            rod in place that did not rotate, with a offset cam/cog inserted inside attached to a shaft <br/>
            which rotated when cranked.
            <br/>
            <br/>
            • I shifted to a more simple solution shown in the above sketch: basically a "bobber" connected to <br/>
            the rod, rests on top of an offset cam which is fixed to a shaft and turned by a crank.<br/>
            <br/>
        <br/>
        <br/>
            DESIGN
            <br/>
            After studying dragonfly visuals, I decided I did not want a realistic representation and made a <br/>
            design that reduced the main body to a cube, making the wings and motion the main focus.
<br/>
<br/>
<br/>
'MAKING'
<br/>

GOALS<br/>
3D print the body cube and the bobber that will be fitted to the base of the steel rod.<br/><br/>

• I aquired a steel rod roughly 1.18mm thick (sourced from Hobby Town)<br/><br/>

• BOBBER: In Rhino I make the bobber by creating a circle 10mm in diamter that I extrude and cap. This <br/>
seems a good size to rest on a 3mm thick CAM. I create a hole in the middle using a solid cylinder <br/>
(diameter 1.22) and boolean difference command—this is where the rod will fit in place on the bobber.<br/><br/>
With 3D printing I discover the hole isn't large enough, which informs the diameter for the shaft <br/>
when I make the body-cube in Rhino.
<br/>
• In Rhino I turn a mesh cube into a solid cube by extruding and capping a rectangle. Then create <br/>
a solid cylinder with dimaeter of 1.30, where the rod will be inserted. Again, with printing the hole<br/>
closes in and is not large enough. I end up drilling the opening in both bobber and body a bit wider, the <br/>
result is a loose fit which I think I can make work.<br/>
<br/><br/>
</p>
<p>
<img src="10-1-2_FirstBobber.png" width=600></a>
</p>
<br/>
<p>
<img src="10-1_First-body-CAM.JPG" width=600></a>
</p>
<p>
You can see how little the 3D printed cylinder shaped bobber is, in the above photo. I didn't think the  <br/>
"bobber" that rests on the CAM had to be much bigger than the width of the CAM(3mm).
<br/>
I was wrong—I needed a larger flat bobber that would smootlhy rise and fall without falling off the CAM.<br/>
But this original bobber became my solution along with an extra body bead, for maintaining a perfectly verticle<br/>
shaft motion.<br/>
<p>
<img src="10-1-3_vs2Rhino.png" width=600></a>
</p>
<p>
  I 3D printed 3 versions of the body bead, this rhino file shows the last, with tiny shaft-openings on the sides where I intend<br/>
  to insert andn glue small metal earring pin with a loop on the end, as a evolving idea for how to attach wings in the end.<br/>
  This time the shaft (verticle) opening at center for the steel rod is 1.40—--and is the right fit for the steel rod, without needing —<br/>
  to drill—but the other horizontal "shafts" totally filled in, no possibility of inserting the earring pin.—<br/>
</p>
<p>
<img src="10-1-1_2nd3dBody.JPG" width=600></a>
</p>
<p>
<img src="10_doneMecha.JPG" width=600></a>
</p>
 <br/>
  <br/>
<p>
  You can see in the above image that I make a two layer BOBBER from wood with a 1.17mm hole at the center of one, <br/>
  which is deliberate for holding the base of the 1.18mm mm rod in place. It worked, but I needed the 3D bobber  <br/>
  help keep the steel rod from wavering back and forth when pushed upward/downward.
  <br/>
  <br/>Also note that I use/glue one of the extra 3D printed body cube to act as a "guide" to keep<br/>
  the steel rod in alignment verticle. Note: it was important that neither support created friction interrupting <br/>
  the upn and down flow of the steel rod.<br/>
</p>
 <br/>
  <br/>
<p>
<img src="10-4_WoodKerfTest.png" width=600></a>
</p>
<br/>
 <br/>
 <p>
  GOAL: LASER CUT FITTED BOX
  <br/>
  From a standpoint of time efficiency, I create a box pattern with the help of a Online box-maker.<br/>
  I tailor it to my needs and test the fit on a piece of scrap:<br/><br/>
  Size of box: 70mm x 100mm x 70mm<br/>
  Kerf: .007 <br/>
  Rule: 001<br/>
  <br/>
  RESULT: When I lasercut my nice hardwood board the fit was loose. A kerf issue. <br/>
  <br/><br/>
  The above and below visual is are evidence of my struggle to get the box to be a snugh fit together.  <br/>

  I ended up using a inferior wood material in the end because I wasn't successful when cutting the (pretty) <br/>
  Alder hardwood. Sad!<br/><br/>
  The final box has a kerf of .002
</p>
<br/>
 <br/>
<p>
<img src="10-2_BoxMaking.JPG" width=600></a>
</p>
<p>
<img src="10_FirstWingImg.png" width=600></a><img src="10_FirstWingsBurn.png" width=600></a>
</p>
<p>
<br/>
 GOAL: Lasercut Paper Wings.<br/>
 • I use Adobe Illustrator and source a vector file for lace wings online. I adapt the vector file<br/>
 of the wings to make it work for my goals, one big change was adding a solid area for fitting them <br/>
 onto the rod in "spindle" fashion.
 <br/>
 <br/>
 My first choice for material became this pretty gray luminescent birch veneer for the wings. I burn up a <br/>
 lot of that veneer! The issue stemmed from two things: Lasercutter settings and the artwork being overly delicate.<br/>
 • settings that worked were 25 speed, 50 power,30 frequency.<br/>
 <br/>
 • Below is the Shutterstock source for my final wing art, that worked.
</p>
<p>
<img src="10_FnlDragonFly.jpg" width=600></a>
</p>
<p>
<img src="10_AIWings.png" width=900></a>
</p>
<p>
  I was able to manipulate the stock art to become what I needed for attaching to the body-bead. I created <br/>
  the one-piece version as a back-up plan for if I wasn't successful solving for making hinged/moveable wings.<br/>
<p>
<img src="10_CuttingWings.JPG" width=600></a>
</p>
<p>
<img src="10_GoodWings.JPG" width=600></a>
</p>
<p>
I was ultimately delighted with how the wings turned out.
</p>
<p>
<img src="10_cutCamWashers.JPG" width=600></a>
</p>
<p>
THE CAM and WASHERS. The CAM is 40mm in diameter. The center hole is a fracton bigger than the 3mm dowel, and was <br/>
perfectly tight—I did not need glue to hold the CAM firmly in the desired central place on the dowel. The washers <br/>
(cut at the same diameter as CAM) worked perfectly without needing glue.
<br/>
</p>
<p>
<img src="10_Shaft.JPG" width=600></a>
<p>
  <br/>
  <br/>
CUT CRANK SHAFT: 30mm wood dowel from hobby store<br/>
<br/>
<br/>
ROD<br/>
 A 1.8mm steel rod. I made a cut that was based on visual estimation.<br/>
</p>
</p>
<p>
<img src="10_RodCut.JPG" width=600></a>
</p>
<p>
<img src="10_doneMecha.JPG" width=600></a>
<p>
Mechanism Assembled<br/>
One of the most challenging aspects of assembly was getting the wire supports for the wings in place. I used a <br/>
gripper tool to straighten a thin wire that came from a spool. I ran it underneath  the cover  and relied on the pressure fit<br/>
of the snap fit cover to hold them in place : this worked because of deliberately keeping the kerf for the cover a bit loose.
</p>
<p>
<img src="" width=600></a>
</p>
<p>
<img src="10_BEST.JPG" width=600></a>
</p>
<p>
MY DRAGONFLY AUTOMATON<br/>
It was super satisfying when all these many pieces when assembled, worked together beautifully. The tolerances were <br/>
all good, the motion was smooth.
<br/>
<br/>
I adhere the wings with tiny magnets that sit over   the steel  rod going through the center of the body bead.<br/>
I hoped this solution would work because the magnets remind me of the oversized eyes of the dragonfly.<br/>
<br/>
I did not need to use the below bead made from sculpey—because the magnet /paper hinge solution for attaching my<br/>
wings worked. However, another solution could be attaching the wings like earrings to the body of dragonfly.
</p>
<p>
<img src="10_backUP.JPG" width=600></a>
</p>
